#############################################################################
#                                                                           #
#                        DynamicChestShop config.yml                        #
#                        Generated for version @version@                    #
#                                                                           #
#############################################################################

#########################################
#                Storage                #
#########################################

Storage:
  # Possible options:
  #
  #   Remote databases - require connection information to be configured below
  #   -> MySQL
  #   -> MariaDB (preferred over MySQL)
  #   -> PostgreSQL
  #
  #   Flatfile/local database - don't require any extra configuration
  #   -> SQLite
  StorageMethod: PostgreSQL

  DatabaseSettings:
    # Define the address and port for the database.
    # - The standard DB engine port is used by default
    #   (MySQL: 3306, PostgreSQL: 5432, MongoDB: 27017)
    # - Specify as "host:port" if differs
    Address: "localhost:5432"
    Database: dynamicchestshop

    # Credentials for the database.
    Username: dynamicchestshop
    Password: 'dynamicchestshop'

#########################################
#                General                #
#########################################

General:
  # The plugin language
  Language: en

  # Plugin chat prefix
  Prefix: "&cAdminShop&f: "

#  # Choose in which mode should plugin function:
#  #  0 = Only infinite shops. The initial chest will be removed and prices will be static
#  #  1 = Only normal shops. The initial chest will act as shop storage and prices will be dynamic
#  #  2 = Both. The initial chest won't be removed. If you want to create infinite shop you will need to destroy the chest manually.
#  Mode: 0

  # How many most used shops should be cached internally
  CachedShops: 100

  # Whether holding SHIFT while interacting works in stacks
  ShiftStacks: false

  # Newbie helper: Blocks creation of chest shops that people can sell to for lower price then buy from
  BlockHigherSellThanBuy: true

  # Will allow transaction of lower amount if:
  # - chestshop gets full
  # - buyer doesn't have enough money
  # - seller doesn't have enough items
  # Price would be adequately scaled
  AllowPartialTransactions: true

  # Steepness of hyperbolic curve used in dynamic pricing, HIGHER NUMBERS = price will change slower (min value is 2000)
  Steepness: 2000

  # Difference between buy and sell prices in % (Diff. is calculated from buy price)
  # For example 0.95 means that sell price will be 95% of buy price...
  Difference: 0.95


###########################################
#           List of permissions           #
###########################################
# Allows creation of Admin Shop and /tad command
#   - dynamicshop.adminshop
# Miscellaneous permission, do not use!
#   - dynamicshop.adminshop.toggle
#
#

