name: DynamicChestShop
version: @version@
main: czechbol.dynamicchestshop.DynamicChestShop
api-version: 1.17
depend: [ Vault ]
authors: [ Czechbol, CrafterSvK ]
description: Chest shop minecraft plugin with static and dynamic pricing
website: https://github.com/Czechbol/DynamicChestShop
